import React from 'react';

import figma from '@figma/code-connect';

import {ActionTooltip} from '../components/ActionTooltip/ActionTooltip';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ActionTooltip,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53632%3A3476',
    {
        props: {
            titleText: figma.string('↳ Title text'),
            description: figma.boolean('Description'),
            descriptionText: figma.string('↳ Description text'),
            title: figma.boolean('Title'),
            shortcut: figma.boolean('Shortcut'),
            state: figma.enum('State', {
                Minimized: 'minimized',
                Full: 'full',
            }),
        },
        example: (props) => <ActionTooltip />,
    },
);
