import React from 'react';
import {ActionsPanel} from '../components/ActionsPanel/ActionsPanel';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ActionsPanel,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53348%3A547352',
    {
        props: {
            button1: figma.boolean('Button 1'),
            button2: figma.boolean('Button 2'),
            button3: figma.boolean('Button 3'),
            button4: figma.boolean('Button 4'),
            moreButton: figma.boolean('More button'),
            closeButton: figma.boolean('Close button'),
            title: figma.boolean('Title'),
            titleText: figma.string('Title text'),
        },
        example: (props) => <ActionsPanel />,
    },
);
