import React from 'react';

import figma from '@figma/code-connect';

import {Alert} from '../components/Alert/Alert';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Alert,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53623%3A196774',
    {
        props: {
            closeButton: figma.boolean('Close button'),
            iconOptional: figma.boolean('Icon (optional)'),
            theme: figma.enum('Theme', {
                Info: 'info',
                Warning: 'warning',
                Danger: 'danger',
                Normal: 'normal',
                Success: 'success',
                Utility: 'utility',
            }),
            view: figma.enum('View', {
                Filled: 'filled',
                Outlined: 'outlined',
            }),
            corners: figma.enum('Corners', {
                Rounded: 'rounded',
                Squared: 'squared',
            }),
        },
        example: (props) => <Alert />,
    },
);
