import React from 'react';
import {AvatarStack} from '../components/AvatarStack/AvatarStack';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    AvatarStack,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53348%3A564209',
    {
        props: {
            contentText: figma.string('↳ Content text'),
            '5Item': figma.boolean('5 item'),
            '4Item': figma.boolean('4 item'),
            '3Item': figma.boolean('3 item'),
            '2Item': figma.boolean('2 item'),
            counter: figma.boolean('Counter'),
            size: figma.enum('Size', {
                XL: 'xl',
                L: 'l',
                M: 'm',
                S: 's',
                XS: 'xs',
            }),
        },
        example: (props) => <AvatarStack />,
    },
);
