import React from 'react';
import {Avatar} from '../components/Avatar/Avatar';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Avatar,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53348%3A563633',
    {
        props: {
            icon: figma.instance('Icon'),
            contentText: figma.string('↳ Content text'),
            customBorder: figma.boolean('Custom border'),
            type: figma.enum('Type', {
                Image: 'image',
                Icon: 'icon',
                Text: 'text',
            }),
            size: figma.enum('Size', {
                '3XS': '3xs',
                '2XS': '2xs',
                XS: 'xs',
                S: 's',
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
            view: figma.enum('View', {
                Filled: 'filled',
                Outlined: 'outlined',
            }),
            theme: figma.enum('Theme', {
                Brand: 'brand',
                Normal: 'normal',
            }),
        },
        example: (props) => <Avatar />,
    },
);
