import React from 'react';

import figma from '@figma/code-connect';

import {Breadcrumbs} from '../components/Breadcrumbs/Breadcrumbs';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Breadcrumbs,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53593%3A3494',
    {
        props: {
            nestingPage5: figma.boolean('Nesting page 5'),
            nestingPage4: figma.boolean('Nesting page 4'),
            nestingPage3: figma.boolean('Nesting page 3'),
            nestingPage2: figma.boolean('Nesting page 2'),
            nestingPage1: figma.boolean('Nesting page 1'),
        },
        example: (props) => <Breadcrumbs />,
    },
);
