import React from 'react';

import figma from '@figma/code-connect';

import {BreadcrumbsItem} from '../components/Breadcrumbs/BreadcrumbsItem';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    BreadcrumbsItem,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53593%3A3535',
    {
        props: {
            pageText: figma.string('Page text'),
            expand: figma.boolean('Expand'),
        },
        example: (props) => <BreadcrumbsItem />,
    },
);
