import React from 'react';
import {Buttons} from '../components/legacy/Popover/components/Buttons/Buttons';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Buttons,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53634%3A108329',
    {
        props: {
            button2: figma.boolean('Button 2'),
            button1: figma.boolean('Button 1'),
            layout: figma.enum('Layout', {
                Horizontal: 'horizontal',
                Vertical: 'vertical',
            }),
        },
        example: (props) => <Buttons />,
    },
);
