import React from 'react';
import {Button} from '../components/Button/Button';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Button,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53098%3A497062',
    {
        props: {
            startIcon: figma.instance(' ↳ Start icon'),
            startIcon: figma.boolean('Start icon'),
            endIcon: figma.boolean('End icon'),
            endIcon: figma.instance(' ↳ End icon'),
            content: figma.string('Content'),
            view: figma.enum('View', {
                Normal: 'normal',
                Action: 'action',
                Outline: 'outline',
                'Outline-info': 'outline-info',
                'Outlined-success': 'outlined-success',
                'Outlined-warning': 'outlined-warning',
                'Outline-danger': 'outline-danger',
                'Outline-utility': 'outline-utility',
                'Outlined-action': 'outlined-action',
                Flat: 'flat',
                'Flat-info': 'flat-info',
                'Flat-success': 'flat-success',
                'Flat-warning': 'flat-warning',
                'Flat-danger': 'flat-danger',
                'Flat-utility': 'flat-utility',
                'Flat-action': 'flat-action',
                'Flat-secondary': 'flat-secondary',
                Raised: 'raised',
                'Normal-contrast': 'normal-contrast',
                'Outline-contrast': 'outline-contrast',
                'Flat-contrast': 'flat-contrast',
            }),
            size: figma.enum('Size', {
                XS: 'xs',
                S: 's',
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Hover: 'hover',
                Disabled: 'disabled',
                Loading: 'loading',
                Selected: 'selected',
            }),
            iconOnly: figma.boolean('Icon only'),
        },
        example: (props) => {
            return (
                <Button
                    state={props.state}
                    size={props.size}
                    view={props.view}
                    content={props.content}
                    iconOnly={props.iconOnly}
                />
            );
        },
    },
);
