import React from 'react';

import figma from '@figma/code-connect';

import Card from '../components/Card/__stories__/Card.stories';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Card,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53349%3A612719',
    {
        props: {
            type: figma.enum('Type', {
                'With themes': 'with-themes',
                'Selectable card': 'selectable-card',
                Raised: 'raised',
                'Raised+Action': 'raised-action',
            }),
        },
        example: (props) => <Card />,
    },
);
