import figma from '@figma/code-connect';

import {Checkbox} from '../components/Checkbox/Checkbox';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Checkbox,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53103%3A9376',
    {
        props: {
            contentText: figma.string('↳ Content text'),
            content: figma.boolean('Content'),
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Hover: 'hover',
                Disabled: 'disabled',
            }),
            checked: figma.boolean('Checked'),
            indeterminate: figma.boolean('Indeterminate'),
        },
        example: ({size, checked, state, indeterminate, content, contentText}) => {
            return (
                <Checkbox
                    size={size}
                    state={state}
                    checked={checked}
                    indeterminate={indeterminate}
                    content={content}
                    contentText={contentText}
                />
            );
        },
    },
);
