import React from 'react';
import {CollapseActions} from '../components/ActionsPanel/components/CollapseActions';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    CollapseActions,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53621%3A120273',
    {
        props: {
            counter: figma.string('↳ Counter'),
            state: figma.enum('State', {
                Default: 'default',
                Hovered: 'hovered',
            }),
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
        },
        example: (props) => <CollapseActions />,
    },
);
