import React from 'react';

import figma from '@figma/code-connect';

import {Content} from '../components/legacy/Popover/components/Content/Content';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Content,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53351%3A624682',
    {
        props: {
            value: figma.string('Value'),
            endIcon: figma.instance('↳ End icon'),
            endIcon: figma.boolean('End Icon'),
            startIcon: figma.boolean('Start icon'),
            startIcon: figma.instance('↳ Start icon'),
            label5: figma.boolean('Label 5'),
            label4: figma.boolean('Label 4'),
            label3: figma.boolean('Label 3'),
            label2: figma.boolean('Label 2'),
            type: figma.enum('Type', {
                Text: 'text',
                User: 'user',
                RadioButton: 'radiobutton',
                Label: 'label',
                Loader: 'loader',
                Skeleton: 'skeleton',
            }),
        },
        example: (props) => <Content />,
    },
);
