import React from 'react';
import {DefinitionList} from '../components/DefinitionList/DefinitionList';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    DefinitionList,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53351%3A624752',
    {
        props: {
            title: figma.string('Title'),
            helpIcon: figma.boolean('Help icon'),
            dots: figma.boolean('Dots'),
            size: figma.enum('Size', {
                S: 's',
                M: 'm',
                Responsive: 'responsive',
            }),
            layout: figma.enum('Layout', {
                Vertical: 'vertical',
                Horizontal: 'horizontal',
            }),
        },
        example: (props) => <DefinitionList />,
    },
);
