import React from 'react';
import {Dialog} from '../components/Dialog/Dialog';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Dialog,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53634%3A54650',
    {
        props: {
            scrollbar: figma.boolean('Scrollbar'),
            dividerTop: figma.boolean('Divider top'),
            additionalButton: figma.boolean('Additional button'),
            secondButton: figma.boolean('Second button'),
            mainButton: figma.boolean('Main button'),
            dividerBottom: figma.boolean('Divider bottom'),
            description: figma.boolean('Description'),
            swaparea: figma.boolean('Swap-area'),
            swaparea: figma.instance('↳ Swap-area'),
            size: figma.enum('Size', {
                S: 's',
                M: 'm',
                L: 'l',
                Manual: 'manual',
            }),
            background: figma.boolean('Background'),
        },
        example: (props) => <Dialog />,
    },
);
