import React from 'react';

import figma from '@figma/code-connect';

import {DropdownMenu} from '../components/DropdownMenu/DropdownMenu';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    DropdownMenu,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53431%3A562412',
    {
        props: {
            scroll: figma.boolean('Scroll'),
            type: figma.enum('Type', {
                'With icons': 'with-icons',
                Basic: 'basic',
                Grouped: 'grouped',
            }),
            size: figma.enum('Size', {
                XL: 'xl',
                L: 'l',
                M: 'm',
                S: 's',
            }),
        },
        example: (props) => <DropdownMenu />,
    },
);
