import React from 'react';

import figma from '@figma/code-connect';

import {FilePreview} from '../components/FilePreview/FilePreview';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    FilePreview,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53380%3A191734',
    {
        props: {
            button: figma.boolean('Button'),
            button2: figma.boolean('Button 2'),
            description: figma.boolean('Description'),
            state: figma.enum('State', {
                Default: 'default',
                Hover: 'hover',
            }),
        },
        example: (props) => <FilePreview />,
    },
);
