import React from 'react';

import figma from '@figma/code-connect';

import {Hotkey} from '../components/Hotkey/Hotkey';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Hotkey,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53551%3A18667',
    {
        props: {
            item2: figma.boolean('Item 2'),
            item3: figma.boolean('Item 3'),
            item4: figma.boolean('Item 4'),
            item5: figma.boolean('Item 5'),
            platform: figma.enum('Platform', {
                Mac: 'mac',
                PC: 'pc',
            }),
        },
        example: (props) => <Hotkey />,
    },
);
