import React from 'react';

import figma from '@figma/code-connect';

import {Label} from '../components/Label/Label';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Label,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53380%3A170630',
    {
        props: {
            endIconHover: figma.boolean('End icon hover'),
            value: figma.boolean('Value'),
            endIcon: figma.boolean('End icon'),
            valueText: figma.string('↳ Value text'),
            keyText: figma.string('Key text'),
            endIcon: figma.instance('↳ End icon'),
            icon: figma.boolean('Icon'),
            icon: figma.instance('↳ Icon'),
            size: figma.enum('Size', {
                XS: 'xs',
                S: 's',
                M: 'm',
            }),
            theme: figma.enum('Theme', {
                Normal: 'normal',
                Info: 'info',
                Success: 'success',
                Warning: 'warning',
                Danger: 'danger',
                Unknown: 'unknown',
                Utility: 'utility',
                Clear: 'clear',
            }),
            hovered: figma.boolean('Hovered'),
            iconOnly: figma.boolean('Icon only'),
        },
        example: (props) => <Label />,
    },
);
