import React from 'react';
import {List} from '../components/List/List';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    List,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53389%3A12527',
    {
        props: {
            bottomPannel: figma.boolean('Bottom pannel'),
            topPanel: figma.boolean('Top panel'),
            scroll: figma.boolean('Scroll'),
            item1: figma.boolean('Item 1'),
            item2: figma.boolean('Item 2'),
            item3: figma.boolean('Item 3'),
            item4: figma.boolean('Item 4'),
            item5: figma.boolean('Item 5'),
            item6: figma.boolean('Item 6'),
            item7: figma.boolean('Item 7'),
            item8: figma.boolean('Item 8'),
            item9: figma.boolean('Item 9'),
            item10: figma.boolean('Item 10'),
            type: figma.enum('Type', {
                Basic: 'basic',
                Multiselect: 'multiselect',
                Users: 'users',
                Multiline: 'multiline',
                'Dropdown menu': 'dropdown-menu',
                Sortable: 'sortable',
                Grouped: 'grouped',
            }),
        },
        example: (props) => <List />,
    },
);
