import React from 'react';

import figma from '@figma/code-connect';

import {ListItem} from '../components/List/components/ListItem';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ListItem,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53389%3A11501',
    {
        props: {
            endIcon: figma.boolean('End icon'),
            startIcon: figma.boolean('Start icon'),
            secondaryContent: figma.boolean('Secondary content'),
            sortable: figma.boolean('Sortable'),
            nested: figma.boolean('Nested'),
            counter: figma.boolean('Counter'),
            expanded: figma.boolean('Expanded'),
            checked: figma.boolean('Checked'),
            type: figma.enum('Type', {
                Basic: 'basic',
                User: 'user',
                Multiline: 'multiline',
                Group: 'group',
                Divider: 'divider',
            }),
            size: figma.enum('Size', {
                XL: 'xl',
                L: 'l',
                M: 'm',
                S: 's',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Hover: 'hover',
                Active: 'active',
                Disabled: 'disabled',
            }),
        },
        example: (props) => <ListItem />,
    },
);
