import React from 'react';

import figma from '@figma/code-connect';

import {Loader} from '../components/Loader/Loader';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Loader,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=41187%3A433363',
    {
        props: {
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
                S: 's',
            }),
        },
        example: (props) => <Loader />,
    },
);
