import React from 'react';

import figma from '@figma/code-connect';

import {Overlay} from '../components/Overlay/Overlay';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Overlay,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53623%3A259383',
    {
        props: {
            text: figma.boolean('Text'),
            loader: figma.boolean('Loader'),
            text: figma.string('↳ Text'),
            background: figma.enum('Background', {
                Base: 'base',
                Float: 'float',
            }),
            textAlign: figma.enum('Text align', {
                Vertical: 'vertical',
                Horizontal: 'horizontal',
            }),
        },
        example: (props) => <Overlay />,
    },
);
