import React from 'react';

import figma from '@figma/code-connect';

import {Pagination} from '../components/Pagination/Pagination';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Pagination,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53623%3A336970',
    {
        props: {
            inputPageNumber: figma.boolean('Input page number'),
            grouping: figma.boolean('Grouping'),
            pageNumbers: figma.boolean('Page numbers'),
            type: figma.enum('Type', {
                Default: 'default',
                Compact: 'compact',
                Mobile: 'mobile',
            }),
            pageNumber: figma.enum('Page number', {
                Second: 'second',
                First: 'first',
                Last: 'last',
            }),
        },
        example: (props) => <Pagination />,
    },
);
