import React from 'react';

import figma from '@figma/code-connect';

import {PlaceholderContainer} from '../components/PlaceholderContainer/PlaceholderContainer';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    PlaceholderContainer,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53431%3A1326961',
    {
        props: {
            descriptionText: figma.string('↳ Description text'),
            title: figma.boolean('Title'),
            links: figma.boolean('Links'),
            titleText: figma.string('↳ Title text'),
            buttons: figma.boolean('Buttons'),
            description: figma.boolean('Description'),
            button2: figma.boolean('Button 2'),
            button3: figma.boolean('Button 3'),
            illustrationL: figma.instance('Illustration L'),
            illustrationM: figma.instance('Illustration M'),
            illustrationS: figma.instance('Illustration S'),
            size: figma.enum('Size', {
                S: 's',
                M: 'm',
                L: 'l',
            }),
            direction: figma.enum('Direction', {
                Row: 'row',
                Column: 'column',
            }),
        },
        example: (props) => <PlaceholderContainer />,
    },
);
