import React from 'react';
import {Popover} from '../components/Popover/Popover';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Popover,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53634%3A107901',
    {
        props: {
            buttons: figma.boolean('Buttons'),
            title: figma.boolean('Title'),
            titleText: figma.string('↳ Title text'),
            link: figma.boolean('Link'),
            closeButton: figma.boolean('Close button'),
            size: figma.enum('Size', {
                S: 's',
                L: 'l',
            }),
            theme: figma.enum('Theme', {
                Info: 'info',
                Special: 'special',
                'Announcement (depricated)': 'announcement--depricated-',
            }),
            arrow: figma.enum('Arrow', {
                None: 'none',
                Left: 'left',
                Right: 'right',
                Up: 'up',
                Down: 'down',
            }),
        },
        example: (props) => <Popover />,
    },
);
