import React from 'react';

import figma from '@figma/code-connect';

import {Popup} from '../components/Popup/Popup';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Popup,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53635%3A157588',
    {
        props: {
            pin: figma.enum('Pin', {
                None: 'none',
                Up: 'up',
                Down: 'down',
                Left: 'left',
                Right: 'right',
            }),
        },
        example: (props) => <Popup />,
    },
);
