import React from 'react';
import {Progress, Progress} from '../components/Progress/Progress';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Progress,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53731%3A19811',
    {
        props: {},
        example: (props) => <Progress />,
    },
);

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Progress,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53501%3A11697',
    {
        props: {
            size: figma.enum('Size', {
                M: 'm',
                S: 's',
                XS: 'xs',
            }),
            stack: figma.boolean('Stack'),
        },
        example: (props) => <Progress />,
    },
);
