import React from 'react';

import figma from '@figma/code-connect';

import {Radio} from '../components/Radio/Radio';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Radio,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53131%3A43373',
    {
        props: {
            contentText: figma.string('↳ Content text'),
            content: figma.boolean('Content'),
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Hover: 'hover',
                Disabled: 'disabled',
            }),
            checked: figma.boolean('Checked'),
        },
        example: (props) => <Radio />,
    },
);
