import React from 'react';
import {RadioGroup} from '../components/RadioGroup/RadioGroup';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    RadioGroup,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53131%3A51193',
    {
        props: {
            item3: figma.boolean('Item 3'),
            item4: figma.boolean('Item 4'),
            item5: figma.boolean('Item 5'),
            item6: figma.boolean('Item 6'),
            item7: figma.boolean('Item 7'),
            item8: figma.boolean('Item 8'),
            item9: figma.boolean('Item 9'),
            item10: figma.boolean('Item 10'),
            direction: figma.enum('Direction', {
                Vertical: 'vertical',
                Horizontal: 'horizontal',
            }),
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
        },
        example: (props) => <RadioGroup />,
    },
);
