import React from 'react';

import figma from '@figma/code-connect';

import {Select} from '../components/Select/Select';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Select,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53168%3A66962',
    {
        props: {
            label: figma.boolean('Label'),
            labelText: figma.string('↳ Label text'),
            content: figma.boolean('Content'),
            contentText: figma.string('↳ Content text'),
            errorText: figma.string('Error text'),
            clearIcon: figma.boolean('Clear icon'),
            counter: figma.boolean('Counter'),
            counterValue: figma.string('↳ Counter value'),
            size: figma.enum('Size', {
                S: 's',
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
            state: figma.enum('State', {
                Suggest: 'suggest',
                Default: 'default',
                Hover: 'hover',
                Disabled: 'disabled',
                Active: 'active',
                'Error inline': 'error-inline',
                'Error outline': 'error-outline',
            }),
            view: figma.enum('View', {
                Normal: 'normal',
                Clear: 'clear',
            }),
        },
        example: (props) => <Select />,
    },
);
