import React from 'react';
import {Spin} from '../components/Spin/Spin';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Spin,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=43625%3A494110',
    {
        props: {
            size: figma.enum('size', {
                XS: 'xs',
                S: 's',
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
        },
        example: (props) => <Spin />,
    },
);
