import React from 'react';
import {Stepper} from '../components/Stepper/Stepper';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Stepper,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=55032%3A26305',
    {
        props: {
            step5: figma.boolean('Step 5'),
            step4: figma.boolean('Step 4'),
            step3: figma.boolean('Step 3'),
            size: figma.enum('Size', {
                S: 's',
                M: 'm',
                L: 'l',
            }),
        },
        example: (props) => <Stepper />,
    },
);
