import React from 'react';
import {Switch} from '../components/Switch/Switch';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Switch,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53131%3A64366',
    {
        props: {
            contentText: figma.string('Content text'),
            content: figma.boolean('Content'),
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
            }),
            selected: figma.boolean('Selected'),
            disabled: figma.boolean('Disabled'),
            hovered: figma.boolean('Hovered'),
        },
        example: (props) => {
            return (
                <Switch
                    size={props.size}
                    selected={props.selected}
                    content={props.content}
                    disabled={props.disabled}
                    hovered={props.hovered}
                />
            );
        },
    },
);
