import React from 'react';

import figma from '@figma/code-connect';

import {Tab} from '../components/tabs/Tab';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Tab,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53621%3A120183',
    {
        props: {
            counter: figma.boolean('Counter'),
            startIcon: figma.boolean('Start icon'),
            label: figma.boolean('Label'),
            text: figma.string('↳ Text'),
            ounter: figma.string('↳ Сounter'),
            icon: figma.instance('↳ Icon'),
            state: figma.enum('State', {
                Default: 'default',
                Selected: 'selected',
                Hovered: 'hovered',
                Disabled: 'disabled',
            }),
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
        },
        example: (props) => <Tab />,
    },
);
