import React from 'react';
import {Table} from '../components/Table/Table';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Table,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53938%3A38750',
    {
        props: {
            column1: figma.boolean('Column 1'),
            column4: figma.boolean('Column 4'),
            column3: figma.boolean('Column 3'),
            column2: figma.boolean('Column 2'),
            column5: figma.boolean('Column 5'),
            column6: figma.boolean('Column 6'),
            column7: figma.boolean('Column 7'),
            column8: figma.boolean('Column 8'),
            column1Type: figma.instance('↳ Column 1 type'),
            actions: figma.boolean('Actions'),
            tableSettings: figma.boolean('↳ Table Settings'),
            cellButtons: figma.boolean('↳ Cell Buttons'),
            column2Type: figma.instance('↳ Column 2 type'),
            column3Type: figma.instance('↳ Column 3 type'),
            column4Type: figma.instance('↳ Column 4 type'),
            column5Type: figma.instance('↳ Column 5 type'),
            column6Type: figma.instance('↳ Column 6 type'),
            column7Type: figma.instance('↳ Column 7 type'),
            column8Type: figma.instance('↳ Column 8 type'),
            heckboxes: figma.boolean('Сheckboxes'),
            dividers: figma.boolean('Dividers'),
            column9: figma.boolean('Column 9'),
            column10: figma.boolean('Column 10'),
            column9Type: figma.instance('↳ Column 9 type'),
            column10Type: figma.instance('↳ Column 10 type'),
        },
        example: (props) => <Table />,
    },
);
