import React from 'react';

import figma from '@figma/code-connect';

import {Tabs} from '../components/legacy/Tabs/Tabs';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Tabs,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53621%3A120305',
    {
        props: {
            item4: figma.boolean('Item 4'),
            item6: figma.boolean('Item 6'),
            item8: figma.boolean('Item 8'),
            item10: figma.boolean('Item 10'),
            item9: figma.boolean('Item 9'),
            item7: figma.boolean('Item 7'),
            item5: figma.boolean('Item 5'),
            item3: figma.boolean('Item 3'),
            collapseTab: figma.boolean('Collapse tab'),
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
        },
        example: (props) => <Tabs />,
    },
);
