import React from 'react';
import {TextInput} from '../components/controls/TextInput/TextInput';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    TextInput,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53175%3A148339',
    {
        props: {
            content: figma.boolean('Content'),
            label: figma.boolean('Label'),
            labelText: figma.string('↳ Label text'),
            clearButton: figma.boolean('Clear button'),
            button1: figma.boolean('Button 1'),
            button2: figma.boolean('Button 2'),
            additional: figma.boolean('Additional'),
            additionalText: figma.string('↳ Additional text'),
            errorIcon: figma.boolean('Error icon'),
            contentText: figma.string('↳ Content text'),
            errorText: figma.string('Error text'),
            startIcon: figma.boolean('Start icon'),
            rightSide: figma.boolean('Right side'),
            size: figma.enum('Size', {
                S: 's',
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
            state: figma.enum('State', {
                Suggest: 'suggest',
                Default: 'default',
                Hovered: 'hovered',
                Selected: 'selected',
                Disabled: 'disabled',
                'Error inline': 'error-inline',
                'Error outline': 'error-outline',
            }),
            view: figma.enum('View', {
                Normal: 'normal',
                Clear: 'clear',
            }),
        },
        example: (props) => {
            return <TextInput state={props.state} size={props.size} view={props.view} />;
        },
    },
);
