import React from 'react';

import figma from '@figma/code-connect';

import {TextArea} from '../components/controls/TextArea/TextArea';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    TextArea,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53172%3A41697',
    {
        props: {
            content: figma.boolean('Content'),
            contentText: figma.string('↳ Content text'),
            clearButton: figma.boolean('Clear button'),
            errorIcon: figma.boolean('Error icon'),
            errorText: figma.string('Error text'),
            additional: figma.boolean('Additional'),
            additionalText: figma.string('↳ Additional text'),
            size: figma.enum('Size', {
                S: 's',
                M: 'm',
                L: 'l',
                XL: 'xl',
            }),
            state: figma.enum('State', {
                Suggest: 'suggest',
                Default: 'default',
                Hover: 'hover',
                Selected: 'selected',
                Disabled: 'disabled',
                'Error inline': 'error-inline',
                'Error outline': 'error-outline',
            }),
            view: figma.enum('View', {
                Normal: 'normal',
                Clear: 'clear',
            }),
        },
        example: (props) => (
            <TextArea
                size={props.size}
                state={props.state}
                content={props.content}
                contentText={props.contentText}
                view={props.view}
            />
        ),
    },
);
