import React from 'react';
import Theme from '../components/theme/__stories__/Theme.stories';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Theme,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53349%3A612738',
    {
        props: {
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
            }),
            theme: figma.enum('Theme', {
                Normal: 'normal',
                Danger: 'danger',
                Warning: 'warning',
                Info: 'info',
                Success: 'success',
                Utility: 'utility',
            }),
            view: figma.enum('View', {
                Outlined: 'outlined',
                Filled: 'filled',
            }),
        },
        example: (props) => <Theme />,
    },
);
