import React from 'react';

import figma from '@figma/code-connect';

import Toaster from '../components/Toaster/__stories__/Toaster.stories';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Toaster,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53623%3A302211',
    {
        props: {
            titleText: figma.string('↳ Title text'),
            description: figma.boolean('Description'),
            closeButton: figma.boolean('Close button'),
            descriptionText: figma.string('↳ Description text'),
            title: figma.boolean('Title'),
            icon: figma.boolean('Icon'),
            buttons: figma.boolean('Buttons'),
            button2: figma.boolean('Button 2'),
            icon: figma.instance('↳ Icon'),
            button1: figma.boolean('Button 1'),
            theme: figma.enum('Theme', {
                Normal: 'normal',
                Info: 'info',
                Success: 'success',
                Warning: 'warning',
                Danger: 'danger',
                Utility: 'utility',
            }),
        },
        example: (props) => <Toaster />,
    },
);
