import React from 'react';

import figma from '@figma/code-connect';

import {Toc} from '../components/Toc/Toc';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Toc,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53624%3A369932',
    {
        props: {
            item3: figma.boolean('Item 3'),
            item4: figma.boolean('Item 4'),
            item5: figma.boolean('Item 5'),
            item6: figma.boolean('Item 6'),
            item7: figma.boolean('Item 7'),
            item8: figma.boolean('Item 8'),
            item9: figma.boolean('Item 9'),
            item10: figma.boolean('Item 10'),
            item11: figma.boolean('Item 11'),
            item12: figma.boolean('Item 12'),
            item13: figma.boolean('Item 13'),
            item14: figma.boolean('Item 14'),
            item15: figma.boolean('Item 15'),
            scrollBar: figma.boolean('Scroll bar'),
        },
        example: (props) => <Toc />,
    },
);
