import React from 'react';

import figma from '@figma/code-connect';

import {TocItem} from '../components/Toc/TocItem/TocItem';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    TocItem,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53624%3A369881',
    {
        props: {
            text: figma.string('Text'),
            state: figma.enum('State', {
                Default: 'default',
                Hovered: 'hovered',
                Selected: 'selected',
            }),
            nested: figma.boolean('Nested'),
        },
        example: (props) => <TocItem />,
    },
);
