import React from 'react';
import {Tooltip} from '../components/Tooltip/Tooltip';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    Tooltip,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53635%3A172934',
    {
        props: {
            contentText: figma.string('Content text'),
        },
        example: (props) => <Tooltip />,
    },
);
