import React from 'react';
import {UserLabel} from '../components/UserLabel/UserLabel';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    UserLabel,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53452%3A744016',
    {
        props: {
            contentText: figma.string('↳ Content text'),
            closable: figma.boolean('Closable'),
            secondartyContentText: figma.string('↳ Secondarty content text'),
            secondaryContent: figma.boolean('Secondary content'),
            type: figma.enum('Type', {
                Person: 'person',
                Email: 'email',
                Empty: 'empty',
                Image: 'image',
            }),
            theme: figma.enum('Theme', {
                Clear: 'clear',
                Outlined: 'outlined',
            }),
            size: figma.enum('Size', {
                M: 'm',
                '2XS': '2xs',
                L: 'l',
                S: 's',
                XL: 'xl',
                XS: 'xs',
                '3XS': '3xs',
            }),
        },
        example: (props) => <UserLabel />,
    },
);
