import React from 'react';
import {selectionColumnId} from '../components/Table/hoc/withTableSelection/withTableSelection';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    selectionColumnId,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53349%3A612842',
    {
        props: {
            size: figma.enum('Size', {
                M: 'm',
                L: 'l',
            }),
            state: figma.enum('State', {
                Default: 'default',
                Selected: 'selected',
                Hovered: 'hovered',
            }),
        },
        example: (props) => <selectionColumnId />,
    },
);
