import React from 'react';

import figma from '@figma/code-connect';

import {WithTableSettingsCustomActionsShowcase} from '../components/Table/__stories__/WithTableSettingsCustomActions/WithTableSettingsCustomActions';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    WithTableSettingsCustomActionsShowcase,
    'https://www.figma.com/design/1xmAVpNG0xrBD9LqsOYWSk/Gravity-UI-MCP-Fun?node-id=53551%3A18696',
    {
        props: {
            symbol: figma.enum('Symbol', {
                '⇥ Tab': '--tab',
                '⇧ Shift': '--shift',
                '⌃ Control': '--control',
                '⌘ Command': '--command',
                '⌥ Option': '--option',
                '⌫ Backspace': '--backspace',
                '⎋ Esq': '--esq',
                '▲ Up': '--up',
                '▶ Right': '--right',
                '▼ Down': '--down',
                '◀ Left': '--left',
                Text: 'text',
            }),
        },
        example: (props) => <WithTableSettingsCustomActionsShowcase />,
    },
);
